title: robotodo
execute:
  execute_notebooks: false

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - 'references.bib'

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  # TODO use skipif
  #- 'sphinx.ext.doctest'
  #- 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.graphviz'
  - 'sphinx.ext.inheritance_diagram'
  - 'sphinxcontrib.mermaid'
  config:
    add_module_names: False
    autosummary_generate: True
    autodoc_default_options:
      members: true
      #undoc-members: true
      #private-members: true
      #special-members: true
      #inherited-members: true
      show-inheritance: true
    graphviz_output_format: 'svg'